import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/sass/reset.scss'
import '@/sass/global.scss'
import AuthContext from '@/context/AuthContext'
import { Suspense } from 'react'
import LoadingSpinner from '@/components/icons/spinner/LoadingSpinner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
